INSERT INTO Classroom (ClassroomID, Capacity, Room_Type, Facilities)
VALUES
    (501, 30, 'Lecture Hall', 'Projector, Whiteboard'),
    (502, 25, 'Science Lab', 'Lab Equipment'),
    (503, 40, 'Art Studio', 'Easels, Paints'),
    (504, 35, 'Computer Lab', 'Computers, Printers'),
    (505, 50, 'Gymnasium', 'Basketball Hoops, Exercise Mats'),
    (506, 20, 'Music Room', 'Piano, Music Stands'),
    (507, 30, 'Conference Room', 'Conference Table, Chairs'),
    (508, 25, 'Language Lab', 'Headsets, Microphones'),
    (509, 40, 'Drama Studio', 'Stage, Lighting Equipment'),
    (510, 35, 'Library', 'Bookshelves, Reading Area'),
    (511, 30, 'Math Lab', 'Math Manipulatives, Graphing Calculators'),
    (512, 20, 'Robotics Lab', 'Robots, Tools'),
    (513, 45, 'Cafeteria', 'Tables, Chairs, Kitchen'),
    (514, 25, 'History Room', 'Maps, Artifacts'),
    (515, 30, 'Outdoor Garden', 'Plants, Benches'),
    (516, 35, 'Psychology Lab', 'Experiment Stations, Observation Room'),
    (517, 40, 'Chemistry Lab', 'Chemicals, Safety Equipment'),
    (518, 30, 'Film Studio', 'Cameras, Lighting'),
    (519, 25, 'Home Economics Room', 'Stoves, Kitchen Utensils'),
    (520, 50, 'Sports Field', 'Goalposts, Track'),
    (521, 30, 'Physics Lab', 'Physics Apparatus, Laser'),
    (522, 20, 'Journalism Room', 'Computers, Editing Software'),
    (523, 35, 'Health Education Room', 'Skeleton Model, Charts'),
    (524, 40, 'Robotics Workshop', 'Workbenches, 3D Printers'),
    (525, 30, 'Greenhouse', 'Planting Beds, Potting Soil'),
    (526, 25, 'Astronomy Observatory', 'Telescope, Star Charts'),
    (527, 30, 'Virtual Reality Lab', 'VR Headsets, Simulation Software'),
    (528, 35, 'Business Classroom', 'Computers, Whiteboard'),
    (529, 40, 'Language Arts Room', 'Bookshelves, Reading Nooks'),
    (530, 45, 'Dance Studio', 'Mirrors, Dance Floor');
