INSERT INTO Teacher (TeacherID, First_Name, Last_Name, Title, Subjects_Taught, Level)
VALUES
    (101, 'Mr.', 'Anderson', 'Mathematics', 'Algebra', 'High School'),
    (102, 'Mrs.', 'Miller', 'English', 'Literature', 'Middle School'),
    (103, 'Ms.', 'Johnson', 'Science', 'Biology', 'High School'),
    (104, 'Mr.', 'Davis', 'History', 'World History', 'High School'),
    (105, 'Mrs.', 'Thomas', 'Mathematics', 'Geometry', 'Middle School'),
    (106, 'Mr.', 'Martinez', 'English', 'Grammar', 'High School'),
    (107, 'Miss', 'White', 'Science', 'Chemistry', 'Middle School'),
    (108, 'Dr.', 'Moore', 'Physics', 'Physics', 'High School'),
    (109, 'Mrs.', 'Garcia', 'History', 'U.S. History', 'Middle School'),
    (110, 'Mr.', 'Lee', 'Mathematics', 'Calculus', 'High School'),
    (111, 'Mrs.', 'Perez', 'English', 'Creative Writing', 'Middle School'),
    (112, 'Mr.', 'Hernandez', 'Science', 'Physics', 'High School'),
    (113, 'Ms.', 'Taylor', 'History', 'European History', 'Middle School'),
    (114, 'Mr.', 'Brown', 'Mathematics', 'Statistics', 'High School'),
    (115, 'Mrs.', 'Clark', 'English', 'Literary Analysis', 'Middle School'),
    (116, 'Mr.', 'Wilson', 'Science', 'Environmental Science', 'High School'),
    (117, 'Miss', 'Fisher', 'History', 'Ancient Civilizations', 'Middle School'),
    (118, 'Mr.', 'Hill', 'Mathematics', 'Trigonometry', 'High School'),
    (119, 'Mrs.', 'Wright', 'English', 'Poetry', 'Middle School'),
    (120, 'Mr.', 'Turner', 'Science', 'Astronomy', 'High School'),
    (121, 'Ms.', 'Cooper', 'History', 'Asian History', 'Middle School'),
    (122, 'Mrs.', 'Brooks', 'Mathematics', 'Algebra II', 'High School'),
    (123, 'Mr.', 'Harrison', 'English', 'Shakespearean Literature', 'Middle School'),
    (124, 'Miss', 'Baker', 'Science', 'Geology', 'High School'),
    (125, 'Dr.', 'Ward', 'History', 'Medieval History', 'Middle School'),
    (126, 'Mr.', 'Russell', 'Mathematics', 'Pre-Calculus', 'High School'),
    (127, 'Mrs.', 'Turner', 'English', 'American Literature', 'Middle School'),
    (128, 'Miss', 'Cooper', 'Science', 'Biology II', 'High School'),
    (129, 'Mr.', 'Hill', 'History', 'World Religions', 'Middle School'),
    (130, 'Mrs.', 'Ward', 'Mathematics', 'Statistics II', 'High School');
